# Allow connections from any container on the Docker network
bind 0.0.0.0

# Enable the Append-Only File persistence mode
appendonly yes

#Memory limit 
maxmemory 512mb

# Define the behavior when 'maxmemory' is reached.
# 'allkeys-lru' tells Redis to evict the least recently used (LRU) keys
# first. This is an excellent policy for a cache, as it keeps the most
# relevant and frequently accessed data in memory.
maxmemory-policy allkeys-lru