is_compiled = false
source_filename = "main.js"
executable_filename = "main.js"
chroot_path = "/opt/evalx/runtimes/javascript-v18"
env_vars = { NODE_PATH = "/opt/nodejs/lib/node_modules" }

[compile]
command = ["/usr/bin/node", "main.js"]

[run]
command = ["/usr/bin/nodejs", "main.js"]

[limits]
time_s = 5
memory_kb = 131072 # 128MB
processes = 5