is_compiled = true
source_filename = "main.c"
executable_filename = "main"

[compile]
command = ["/usr/bin/gcc", "-o", "main", "main.c"]

[run]
command = ["./main"]

[limits]
time_s = 10
memory_kb = 262144 # 256MB
processes = 10