is_compiled = true
source_filename = "main.go"
executable_filename = "main"
chroot_path = "/opt/evalx/chroots/go"

[compile]
command = ["/usr/bin/go", "build", "-o", "main", "main.go"]

[run]
command = ["./main"]

[limits]
time_s = 10
memory_kb = 262144
processes = 15