is_compiled = true
source_filename = "main.cpp"
executable_filename = "main"
chroot_path = "/opt/evalx/chroots/cpp/v11"

[compile]
command = ["/usr/bin/g++", "-std=c++11", "-O2", "-o", "main", "main.cpp", "-lm"]
limits = { time_s = 10, memory_kb = 1048576, processes = 500 }

[run]
command = ["./main"]
limits = { time_s = 10, memory_kb = 1048576, processes = 500 }