is_compiled = true
source_filename = "Main.java"
executable_filename = "Main.class"
chroot_path = "/opt/evalx/chroots/java/v24"
mount_paths = ["usr", "lib", "lib64", "bin", "etc", "var", "dev", "proc", "sys"]

[env_vars]
LD_LIBRARY_PATH = "/usr/local/openjdk-24/lib/jli:/usr/local/openjdk-24/lib/server:/usr/local/openjdk-24/lib"
JAVA_HOME = "/usr/local/openjdk-24"
PATH = "/usr/local/openjdk-24/bin:/usr/bin:/bin"

[compile]
command = [
    "/usr/local/openjdk-24/bin/javac",
    "--enable-preview",
    "--release", 
    "24",
    "-J-XX:TieredStopAtLevel=1",
    "-J-Xms512m",
    "-J-Xmx512m",
    "-J-XX:MaxMetaspaceSize=192m",
    "-J-XX:ReservedCodeCacheSize=64m",
    "-J-XX:+UseSerialGC",
    "Main.java",
]
limits = { time_s = 10, memory_kb = 1536000, processes = 150 }

[run]
command = [
    "/usr/local/openjdk-24/bin/java",
    "--enable-preview",
    "-XX:TieredStopAtLevel=1",
    "-Xms512m",
    "-Xmx512m",
    "-XX:MaxMetaspaceSize=192m",
    "-XX:ReservedCodeCacheSize=64m",
    "-XX:+UseSerialGC",
    "-cp",
    "/box",
    "Main",
]
limits = { time_s = 5, memory_kb = 1536000, processes = 150 }